//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ChatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.IChatService", CallbackContract=typeof(Client.ChatServiceReference.IChatServiceCallback))]
    public interface IChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Connect", ReplyAction="http://tempuri.org/IChatService/ConnectResponse")]
        int Connect(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Connect", ReplyAction="http://tempuri.org/IChatService/ConnectResponse")]
        System.Threading.Tasks.Task<int> ConnectAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Disconnect")]
        void Disconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Disconnect")]
        System.Threading.Tasks.Task DisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetActiveLobbies", ReplyAction="http://tempuri.org/IChatService/GetActiveLobbiesResponse")]
        ChatLibrary.LobbyInfo[] GetActiveLobbies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetActiveLobbies", ReplyAction="http://tempuri.org/IChatService/GetActiveLobbiesResponse")]
        System.Threading.Tasks.Task<ChatLibrary.LobbyInfo[]> GetActiveLobbiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateLobby", ReplyAction="http://tempuri.org/IChatService/CreateLobbyResponse")]
        System.Guid CreateLobby(string lobbyName, int creatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateLobby", ReplyAction="http://tempuri.org/IChatService/CreateLobbyResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateLobbyAsync(string lobbyName, int creatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/JoinLobby", ReplyAction="http://tempuri.org/IChatService/JoinLobbyResponse")]
        bool JoinLobby(System.Guid lobbyId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/JoinLobby", ReplyAction="http://tempuri.org/IChatService/JoinLobbyResponse")]
        System.Threading.Tasks.Task<bool> JoinLobbyAsync(System.Guid lobbyId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendLobbyMessage")]
        void SendLobbyMessage(System.Guid lobbyId, int senderId, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendLobbyMessage")]
        System.Threading.Tasks.Task SendLobbyMessageAsync(System.Guid lobbyId, int senderId, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Hit")]
        void Hit(System.Guid lobbyId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Hit")]
        System.Threading.Tasks.Task HitAsync(System.Guid lobbyId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Stand")]
        void Stand(System.Guid lobbyId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Stand")]
        System.Threading.Tasks.Task StandAsync(System.Guid lobbyId, int playerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMessageToClient")]
        void SendMessageToClient(string senderName, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/UpdateLobbyList")]
        void UpdateLobbyList(ChatLibrary.LobbyInfo[] lobbies);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/UpdateGameTable")]
        void UpdateGameTable(string lobbyStatus, string dealerScore, string[] dealerCards, ChatLibrary.PlayerGameState[] players);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceChannel : Client.ChatServiceReference.IChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<Client.ChatServiceReference.IChatService>, Client.ChatServiceReference.IChatService {
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int Connect(string username) {
            return base.Channel.Connect(username);
        }
        
        public System.Threading.Tasks.Task<int> ConnectAsync(string username) {
            return base.Channel.ConnectAsync(username);
        }
        
        public void Disconnect(int id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int id) {
            return base.Channel.DisconnectAsync(id);
        }
        
        public ChatLibrary.LobbyInfo[] GetActiveLobbies() {
            return base.Channel.GetActiveLobbies();
        }
        
        public System.Threading.Tasks.Task<ChatLibrary.LobbyInfo[]> GetActiveLobbiesAsync() {
            return base.Channel.GetActiveLobbiesAsync();
        }
        
        public System.Guid CreateLobby(string lobbyName, int creatorId) {
            return base.Channel.CreateLobby(lobbyName, creatorId);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateLobbyAsync(string lobbyName, int creatorId) {
            return base.Channel.CreateLobbyAsync(lobbyName, creatorId);
        }
        
        public bool JoinLobby(System.Guid lobbyId, int playerId) {
            return base.Channel.JoinLobby(lobbyId, playerId);
        }
        
        public System.Threading.Tasks.Task<bool> JoinLobbyAsync(System.Guid lobbyId, int playerId) {
            return base.Channel.JoinLobbyAsync(lobbyId, playerId);
        }
        
        public void SendLobbyMessage(System.Guid lobbyId, int senderId, string message) {
            base.Channel.SendLobbyMessage(lobbyId, senderId, message);
        }
        
        public System.Threading.Tasks.Task SendLobbyMessageAsync(System.Guid lobbyId, int senderId, string message) {
            return base.Channel.SendLobbyMessageAsync(lobbyId, senderId, message);
        }
        
        public void Hit(System.Guid lobbyId, int playerId) {
            base.Channel.Hit(lobbyId, playerId);
        }
        
        public System.Threading.Tasks.Task HitAsync(System.Guid lobbyId, int playerId) {
            return base.Channel.HitAsync(lobbyId, playerId);
        }
        
        public void Stand(System.Guid lobbyId, int playerId) {
            base.Channel.Stand(lobbyId, playerId);
        }
        
        public System.Threading.Tasks.Task StandAsync(System.Guid lobbyId, int playerId) {
            return base.Channel.StandAsync(lobbyId, playerId);
        }
    }
}
